name: cateringmid
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0 # Paquete HTTP para hacer solicitudes
  keyboard_dismisser: ^3.0.0
  path_provider: ^2.1.5
  google_maps_flutter: ^2.10.0
  shared_preferences: ^2.4.0
  provider: ^6.1.2
  carousel_slider: ^5.0.0
  flutter_datetime_picker: ^1.5.1
  intl: ^0.20.2
  table_calendar: ^3.2.0
  flutter_launcher_icons: ^0.13.1
  geolocator: ^13.0.2
  image_picker: ^1.1.2
  firebase_core: ^3.12.0
  firebase_messaging: ^15.2.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logoinicial.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
    - assets/logo.png
    - assets/LOGOROJO.png
    - assets/incono.png

